files: ^models/

repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.5
    hooks:
    - id: dbt-deps
    - id: dbt-parse
    - id: dbt-docs-generate
      args: ["--cmd-flags", "++no-partial-parse"]
    - id: check-model-has-all-columns
      name: Ensure all models has all columns in the properties file.
      args: ["--catalog", "./target/catalog.json"]
    - id: check-model-columns-have-desc
      name: Ensure models have descriptions in all its columns.
    - id: check-model-has-description
      name: Ensure every model has a description in its yaml file.
    - id: check-source-table-has-description
      name: Ensure every source has a description on the yaml file.
    - id: check-model-has-tests-by-name
      name: Ensure every model has at least one not_null and unique tests
      args: ["--tests", "not_null=1", "unique=1", "--"]
    - id: check-model-has-tests
      name: Ensure every model has at least 2 data-tests configured
      args: ["--test-cnt", "2", "--"]
    - id: check-script-has-no-table-name
      name: Ensure every model uses ref and source macros
    - id: check-model-parents-name-prefix
      exclude: ^models/staging/
      args: ["--whitelist", "stg_", "--"]
    - id: check-model-name-contract
      args: [--pattern, "(dim_|fct_).*"]
      files: models/marts/

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.7
    hooks:
    - id: sqlfluff-lint
      language: python
      # Need these two dependencies.
      # sqlfluff-templater-dbt should match the version of sqlfluff above in rev (pip show sqlfluff-templater-dbt)
      additional_dependencies:
        ["sqlfluff-templater-dbt==3.0.7", "dbt-postgres"]
      args:
        [--config, .sqlfluff]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
