name: CD_job

on:
  push:
    branches:
      - main

env:
  PROD_HOSTNAME: ${{ secrets.PROD_HOSTNAME  }}
  PROD_USER_NAME: ${{ secrets.PROD_USER_NAME  }}
  PROD_PASSWORD: ${{ secrets.PROD_PASSWORD  }}
  PROD_DB_NAME: ${{ secrets.PROD_DB_NAME  }}
  PROD_SCHEMA: ${{ secrets.PROD_SCHEMA  }}
  PYTHON_VERSION: "3.9"
  DBT_DEFAULT_TARGET: prod

jobs:
  deploy:
    name: deploy
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Configure Git Authentication
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions CI"
          git remote set-url origin "https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git"
          git fetch --all
          git checkout main
          git pull origin main

      - name: Debug Git Remote
        run: git remote -v

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Install dbt dependencies
        run: dbt deps

      - name: Debug dbt connection
        run: dbt debug

      - name: dbt build
        run: dbt build -s state:modified+ --state target-defer --defer --fail-fast

  upload_manifest:
    name: Upload Manifest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Configure Git Authentication
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions CI"
          git remote set-url origin "https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git"
          git fetch --all
          git checkout main
          git pull origin main

      - name: Debug Git Remote
        run: git remote -v

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Install dbt dependencies
        run: dbt deps

      - name: Parse dbt project for Production
        run: dbt parse --target prod
        env:
          DBT_PROFILES_DIR: ./

      - name: Prepare Manifest File
        run: |
          mkdir -p target-defer
          if [ -f target/manifest.json ]; then
            mv target/manifest.json target-defer/manifest.json
            echo "Manifest prepared in target-defer/"
          else
            echo "manifest.json not found after dbt parse. Cannot proceed with upload."
            exit 1
          fi

      - name: Commit Manifest
        run: |
          git add target-defer/manifest.json
          if git diff --staged --quiet; then
            echo "No changes to manifest.json to commit."
          else
            git commit -m "[skip ci] Upload manifest.json to branch main"
          fi

      - name: Push Manifest
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          force: true
